server:
  port: 8083
spring:
  application:
    name: "CrediyaReportsMS"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: "local"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  region: ${AWS_REGION:us-east-2}
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT:https://dynamodb.us-east-2.amazonaws.com}
entrypoint:
  sqs:
    region: ${SQS_ENTRYPOINT_REGION:us-east-2}
    queueUrl: ${UPDATE_REPORT_QUEUE_URL:https://sqs.us-east-2.amazonaws.com/812612912253/cola-actualizar-reporte-dynamo}
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
adapter:
  dynamodb:
    region: ${DYNAMODB_REGION:us-east-2}
logging:
  level:
    software:
      amazon:
        awssdk: DEBUG